//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 09:10:35 AM CEST 
//


package io.cloudtrust.keycloak.liquibaseAdapter.pojo.liquibase;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog}addForeignKeyConstraintAttrib"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "addForeignKeyConstraint")
public class AddForeignKeyConstraint {

    @XmlAttribute(name = "baseTableCatalogName")
    protected String baseTableCatalogName;
    @XmlAttribute(name = "baseTableSchemaName")
    protected String baseTableSchemaName;
    @XmlAttribute(name = "baseTableName", required = true)
    protected String baseTableName;
    @XmlAttribute(name = "baseColumnNames", required = true)
    protected String baseColumnNames;
    @XmlAttribute(name = "constraintName", required = true)
    protected String constraintName;
    @XmlAttribute(name = "referencedTableCatalogName")
    protected String referencedTableCatalogName;
    @XmlAttribute(name = "referencedTableSchemaName")
    protected String referencedTableSchemaName;
    @XmlAttribute(name = "referencedTableName", required = true)
    protected String referencedTableName;
    @XmlAttribute(name = "referencedColumnNames", required = true)
    protected String referencedColumnNames;
    @XmlAttribute(name = "deferrable")
    protected String deferrable;
    @XmlAttribute(name = "initiallyDeferred")
    protected String initiallyDeferred;
    @XmlAttribute(name = "deleteCascade")
    protected String deleteCascade;
    @XmlAttribute(name = "onDelete")
    protected FkCascadeActionOptions onDelete;
    @XmlAttribute(name = "onUpdate")
    protected FkCascadeActionOptions onUpdate;
    @XmlAttribute(name = "referencesUniqueColumn")
    protected String referencesUniqueColumn;

    /**
     * Gets the value of the baseTableCatalogName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseTableCatalogName() {
        return baseTableCatalogName;
    }

    /**
     * Sets the value of the baseTableCatalogName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseTableCatalogName(String value) {
        this.baseTableCatalogName = value;
    }

    /**
     * Gets the value of the baseTableSchemaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseTableSchemaName() {
        return baseTableSchemaName;
    }

    /**
     * Sets the value of the baseTableSchemaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseTableSchemaName(String value) {
        this.baseTableSchemaName = value;
    }

    /**
     * Gets the value of the baseTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseTableName() {
        return baseTableName;
    }

    /**
     * Sets the value of the baseTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseTableName(String value) {
        this.baseTableName = value;
    }

    /**
     * Gets the value of the baseColumnNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseColumnNames() {
        return baseColumnNames;
    }

    /**
     * Sets the value of the baseColumnNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseColumnNames(String value) {
        this.baseColumnNames = value;
    }

    /**
     * Gets the value of the constraintName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstraintName() {
        return constraintName;
    }

    /**
     * Sets the value of the constraintName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstraintName(String value) {
        this.constraintName = value;
    }

    /**
     * Gets the value of the referencedTableCatalogName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedTableCatalogName() {
        return referencedTableCatalogName;
    }

    /**
     * Sets the value of the referencedTableCatalogName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedTableCatalogName(String value) {
        this.referencedTableCatalogName = value;
    }

    /**
     * Gets the value of the referencedTableSchemaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedTableSchemaName() {
        return referencedTableSchemaName;
    }

    /**
     * Sets the value of the referencedTableSchemaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedTableSchemaName(String value) {
        this.referencedTableSchemaName = value;
    }

    /**
     * Gets the value of the referencedTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedTableName() {
        return referencedTableName;
    }

    /**
     * Sets the value of the referencedTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedTableName(String value) {
        this.referencedTableName = value;
    }

    /**
     * Gets the value of the referencedColumnNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedColumnNames() {
        return referencedColumnNames;
    }

    /**
     * Sets the value of the referencedColumnNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedColumnNames(String value) {
        this.referencedColumnNames = value;
    }

    /**
     * Gets the value of the deferrable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeferrable() {
        return deferrable;
    }

    /**
     * Sets the value of the deferrable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeferrable(String value) {
        this.deferrable = value;
    }

    /**
     * Gets the value of the initiallyDeferred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiallyDeferred() {
        return initiallyDeferred;
    }

    /**
     * Sets the value of the initiallyDeferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiallyDeferred(String value) {
        this.initiallyDeferred = value;
    }

    /**
     * Gets the value of the deleteCascade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteCascade() {
        return deleteCascade;
    }

    /**
     * Sets the value of the deleteCascade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteCascade(String value) {
        this.deleteCascade = value;
    }

    /**
     * Gets the value of the onDelete property.
     * 
     * @return
     *     possible object is
     *     {@link FkCascadeActionOptions }
     *     
     */
    public FkCascadeActionOptions getOnDelete() {
        return onDelete;
    }

    /**
     * Sets the value of the onDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkCascadeActionOptions }
     *     
     */
    public void setOnDelete(FkCascadeActionOptions value) {
        this.onDelete = value;
    }

    /**
     * Gets the value of the onUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link FkCascadeActionOptions }
     *     
     */
    public FkCascadeActionOptions getOnUpdate() {
        return onUpdate;
    }

    /**
     * Sets the value of the onUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkCascadeActionOptions }
     *     
     */
    public void setOnUpdate(FkCascadeActionOptions value) {
        this.onUpdate = value;
    }

    /**
     * Gets the value of the referencesUniqueColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencesUniqueColumn() {
        return referencesUniqueColumn;
    }

    /**
     * Sets the value of the referencesUniqueColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencesUniqueColumn(String value) {
        this.referencesUniqueColumn = value;
    }

}
