//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 09:10:35 AM CEST 
//


package io.cloudtrust.keycloak.liquibaseAdapter.pojo.liquibase;

import org.w3c.dom.Element;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.namespace.QName;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="property" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="dbms" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="context" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="preConditions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}PreConditionChildren" maxOccurs="unbounded"/>
 *                 &lt;/choice>
 *                 &lt;attribute name="onFailMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="onErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeLogPreconditionErrorOrFail" />
 *                 &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeLogPreconditionErrorOrFail" />
 *                 &lt;attribute name="onSqlOutput" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeLogPreconditionOnSqlOutput" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="changeSet" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="validCheckSum" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog}comment" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="preConditions" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}PreConditionChildren" maxOccurs="unbounded"/>
 *                             &lt;/choice>
 *                             &lt;attribute name="onFailMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="onErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeSetPreconditionErrorOrFail" />
 *                             &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeSetPreconditionErrorOrFail" />
 *                             &lt;attribute name="onSqlOutput" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeLogPreconditionOnSqlOutput" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;choice>
 *                       &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog}tagDatabase"/>
 *                       &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}changeSetChildren" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;/choice>
 *                     &lt;element name="modifySql" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}modifySqlChildren" maxOccurs="unbounded"/>
 *                             &lt;/choice>
 *                             &lt;attribute name="dbms" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="context" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="applyToRollback" type="{http://www.liquibase.org/xml/ns/dbchangelog}booleanExp" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog}changeSetAttributes"/>
 *                   &lt;anyAttribute namespace='##other'/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="include" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="relativeToChangelogFile" type="{http://www.liquibase.org/xml/ns/dbchangelog}booleanExp" />
 *                   &lt;anyAttribute namespace='##other'/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="includeAll" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="relativeToChangelogFile" type="{http://www.liquibase.org/xml/ns/dbchangelog}booleanExp" />
 *                   &lt;attribute name="resourceFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;anyAttribute namespace='##other'/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog}changeLogAttributes"/>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "property",
    "preConditions",
    "changeSetOrIncludeOrIncludeAll"
})
@XmlRootElement(name = "databaseChangeLog")
public class DatabaseChangeLog {

    protected List<Property> property;
    protected DatabaseChangeLog.PreConditions preConditions;
    @XmlElements({
        @XmlElement(name = "changeSet", type = DatabaseChangeLog.ChangeSet.class),
        @XmlElement(name = "include", type = DatabaseChangeLog.Include.class),
        @XmlElement(name = "includeAll", type = DatabaseChangeLog.IncludeAll.class)
    })
    protected List<Object> changeSetOrIncludeOrIncludeAll;
    @XmlAttribute(name = "logicalFilePath")
    protected String logicalFilePath;
    @XmlAttribute(name = "objectQuotingStrategy")
    protected ObjectQuotingStrategy objectQuotingStrategy;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the property property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatabaseChangeLog.Property }
     *
     *
     */
    public List<Property> getProperty() {
        if (property == null) {
            property = new ArrayList<Property>();
        }
        return this.property;
    }

    /**
     * Gets the value of the preConditions property.
     *
     * @return
     *     possible object is
     *     {@link DatabaseChangeLog.PreConditions }
     *
     */
    public DatabaseChangeLog.PreConditions getPreConditions() {
        return preConditions;
    }

    /**
     * Sets the value of the preConditions property.
     *
     * @param value
     *     allowed object is
     *     {@link DatabaseChangeLog.PreConditions }
     *
     */
    public void setPreConditions(DatabaseChangeLog.PreConditions value) {
        this.preConditions = value;
    }

    /**
     * Gets the value of the changeSetOrIncludeOrIncludeAll property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changeSetOrIncludeOrIncludeAll property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChangeSetOrIncludeOrIncludeAll().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatabaseChangeLog.ChangeSet }
     * {@link DatabaseChangeLog.Include }
     * {@link DatabaseChangeLog.IncludeAll }
     *
     *
     */
    public List<Object> getChangeSetOrIncludeOrIncludeAll() {
        if (changeSetOrIncludeOrIncludeAll == null) {
            changeSetOrIncludeOrIncludeAll = new ArrayList<Object>();
        }
        return this.changeSetOrIncludeOrIncludeAll;
    }

    /**
     * Gets the value of the logicalFilePath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLogicalFilePath() {
        return logicalFilePath;
    }

    /**
     * Sets the value of the logicalFilePath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLogicalFilePath(String value) {
        this.logicalFilePath = value;
    }

    /**
     * Gets the value of the objectQuotingStrategy property.
     *
     * @return
     *     possible object is
     *     {@link ObjectQuotingStrategy }
     *
     */
    public ObjectQuotingStrategy getObjectQuotingStrategy() {
        if (objectQuotingStrategy == null) {
            return ObjectQuotingStrategy.LEGACY;
        } else {
            return objectQuotingStrategy;
        }
    }

    /**
     * Sets the value of the objectQuotingStrategy property.
     *
     * @param value
     *     allowed object is
     *     {@link ObjectQuotingStrategy }
     *
     */
    public void setObjectQuotingStrategy(ObjectQuotingStrategy value) {
        this.objectQuotingStrategy = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="validCheckSum" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog}comment" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="preConditions" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}PreConditionChildren" maxOccurs="unbounded"/>
     *                 &lt;/choice>
     *                 &lt;attribute name="onFailMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="onErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeSetPreconditionErrorOrFail" />
     *                 &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeSetPreconditionErrorOrFail" />
     *                 &lt;attribute name="onSqlOutput" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeLogPreconditionOnSqlOutput" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;choice>
     *           &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog}tagDatabase"/>
     *           &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}changeSetChildren" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;/choice>
     *         &lt;element name="modifySql" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}modifySqlChildren" maxOccurs="unbounded"/>
     *                 &lt;/choice>
     *                 &lt;attribute name="dbms" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="context" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="applyToRollback" type="{http://www.liquibase.org/xml/ns/dbchangelog}booleanExp" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog}changeSetAttributes"/>
     *       &lt;anyAttribute namespace='##other'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "validCheckSum",
        "preConditions",
        "tagDatabase",
        "changeSetChildren",
        "modifySql"
    })
    public static class ChangeSet {

        protected List<ValidCheckSum> validCheckSum;
        protected DatabaseChangeLog.ChangeSet.PreConditions preConditions;
        protected TagDatabase tagDatabase;
        @XmlElementRefs({
            @XmlElementRef(name = "sql", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Sql.class, required = false),
            @XmlElementRef(name = "insert", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Insert.class, required = false),
            @XmlElementRef(name = "dropIndex", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropIndex.class, required = false),
            @XmlElementRef(name = "addNotNullConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddNotNullConstraint.class, required = false),
            @XmlElementRef(name = "createView", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateView.class, required = false),
            @XmlElementRef(name = "renameTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RenameTable.class, required = false),
            @XmlElementRef(name = "dropForeignKeyConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropForeignKeyConstraint.class, required = false),
            @XmlElementRef(name = "rollback", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Rollback.class, required = false),
            @XmlElementRef(name = "loadData", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = LoadData.class, required = false),
            @XmlElementRef(name = "dropNotNullConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropNotNullConstraint.class, required = false),
            @XmlElementRef(name = "alterSequence", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AlterSequence.class, required = false),
            @XmlElementRef(name = "dropPrimaryKey", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropPrimaryKey.class, required = false),
            @XmlElementRef(name = "createSequence", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateSequence.class, required = false),
            @XmlElementRef(name = "addForeignKeyConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddForeignKeyConstraint.class, required = false),
            @XmlElementRef(name = "renameView", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RenameView.class, required = false),
            @XmlElementRef(name = "dropProcedure", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropProcedure.class, required = false),
            @XmlElementRef(name = "dropColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropColumn.class, required = false),
            @XmlElementRef(name = "createTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateTable.class, required = false),
            @XmlElementRef(name = "sqlFile", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = SqlFile.class, required = false),
            @XmlElementRef(name = "addUniqueConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddUniqueConstraint.class, required = false),
            @XmlElementRef(name = "dropView", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropView.class, required = false),
            @XmlElementRef(name = "mergeColumns", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = MergeColumns.class, required = false),
            @XmlElementRef(name = "stop", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Stop.class, required = false),
            @XmlElementRef(name = "update", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Update.class, required = false),
            @XmlElementRef(name = "dropTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropTable.class, required = false),
            @XmlElementRef(name = "executeCommand", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ExecuteCommand.class, required = false),
            @XmlElementRef(name = "createIndex", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateIndex.class, required = false),
            @XmlElementRef(name = "addLookupTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddLookupTable.class, required = false),
            @XmlElementRef(name = "modifyDataType", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ModifyDataType.class, required = false),
            @XmlElementRef(name = "addPrimaryKey", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddPrimaryKey.class, required = false),
            @XmlElementRef(name = "addDefaultValue", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddDefaultValue.class, required = false),
            @XmlElementRef(name = "addAutoIncrement", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddAutoIncrement.class, required = false),
            @XmlElementRef(name = "renameColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RenameColumn.class, required = false),
            @XmlElementRef(name = "dropSequence", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropSequence.class, required = false),
            @XmlElementRef(name = "empty", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "loadUpdateData", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = LoadUpdateData.class, required = false),
            @XmlElementRef(name = "addColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddColumn.class, required = false),
            @XmlElementRef(name = "dropAllForeignKeyConstraints", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropAllForeignKeyConstraints.class, required = false),
            @XmlElementRef(name = "dropDefaultValue", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropDefaultValue.class, required = false),
            @XmlElementRef(name = "customChange", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CustomChange.class, required = false),
            @XmlElementRef(name = "createProcedure", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateProcedure.class, required = false),
            @XmlElementRef(name = "comment", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dropUniqueConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropUniqueConstraint.class, required = false),
            @XmlElementRef(name = "delete", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Delete.class, required = false)
        })
        @XmlAnyElement(lax = true)
        protected List<Object> changeSetChildren;
        protected List<ModifySql> modifySql;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "author", required = true)
        protected String author;
        @XmlAttribute(name = "context")
        protected String context;
        @XmlAttribute(name = "dbms")
        protected String dbms;
        @XmlAttribute(name = "runOnChange")
        protected String runOnChange;
        @XmlAttribute(name = "runAlways")
        protected String runAlways;
        @XmlAttribute(name = "failOnError")
        protected String failOnError;
        @XmlAttribute(name = "onValidationFail")
        protected OnChangeSetValidationFail onValidationFail;
        @XmlAttribute(name = "runInTransaction")
        protected String runInTransaction;
        @XmlAttribute(name = "logicalFilePath")
        protected String logicalFilePath;
        @XmlAttribute(name = "objectQuotingStrategy")
        protected ObjectQuotingStrategy objectQuotingStrategy;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the validCheckSum property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the validCheckSum property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValidCheckSum().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DatabaseChangeLog.ChangeSet.ValidCheckSum }
         *
         *
         */
        public List<ValidCheckSum> getValidCheckSum() {
            if (validCheckSum == null) {
                validCheckSum = new ArrayList<ValidCheckSum>();
            }
            return this.validCheckSum;
        }

        /**
         * Gets the value of the preConditions property.
         *
         * @return
         *     possible object is
         *     {@link DatabaseChangeLog.ChangeSet.PreConditions }
         *
         */
        public DatabaseChangeLog.ChangeSet.PreConditions getPreConditions() {
            return preConditions;
        }

        /**
         * Sets the value of the preConditions property.
         *
         * @param value
         *     allowed object is
         *     {@link DatabaseChangeLog.ChangeSet.PreConditions }
         *
         */
        public void setPreConditions(DatabaseChangeLog.ChangeSet.PreConditions value) {
            this.preConditions = value;
        }

        /**
         * Gets the value of the tagDatabase property.
         *
         * @return
         *     possible object is
         *     {@link TagDatabase }
         *
         */
        public TagDatabase getTagDatabase() {
            return tagDatabase;
        }

        /**
         * Sets the value of the tagDatabase property.
         *
         * @param value
         *     allowed object is
         *     {@link TagDatabase }
         *
         */
        public void setTagDatabase(TagDatabase value) {
            this.tagDatabase = value;
        }

        /**
         * Gets the value of the changeSetChildren property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the changeSetChildren property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChangeSetChildren().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Sql }
         * {@link Insert }
         * {@link DropIndex }
         * {@link Element }
         * {@link AddNotNullConstraint }
         * {@link CreateView }
         * {@link RenameTable }
         * {@link DropForeignKeyConstraint }
         * {@link Rollback }
         * {@link LoadData }
         * {@link DropNotNullConstraint }
         * {@link AlterSequence }
         * {@link DropPrimaryKey }
         * {@link CreateSequence }
         * {@link AddForeignKeyConstraint }
         * {@link RenameView }
         * {@link DropProcedure }
         * {@link DropColumn }
         * {@link CreateTable }
         * {@link SqlFile }
         * {@link AddUniqueConstraint }
         * {@link DropView }
         * {@link MergeColumns }
         * {@link Stop }
         * {@link Update }
         * {@link DropTable }
         * {@link ExecuteCommand }
         * {@link CreateIndex }
         * {@link AddLookupTable }
         * {@link Object }
         * {@link ModifyDataType }
         * {@link AddPrimaryKey }
         * {@link AddDefaultValue }
         * {@link AddAutoIncrement }
         * {@link RenameColumn }
         * {@link DropSequence }
         * {@link JAXBElement }{@code <}{@link Object }{@code >}
         * {@link LoadUpdateData }
         * {@link AddColumn }
         * {@link DropAllForeignKeyConstraints }
         * {@link DropDefaultValue }
         * {@link CustomChange }
         * {@link CreateProcedure }
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link DropUniqueConstraint }
         * {@link Delete }
         *
         *
         */
        public List<Object> getChangeSetChildren() {
            if (changeSetChildren == null) {
                changeSetChildren = new ArrayList<Object>();
            }
            return this.changeSetChildren;
        }

        /**
         * Gets the value of the modifySql property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the modifySql property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getModifySql().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DatabaseChangeLog.ChangeSet.ModifySql }
         *
         *
         */
        public List<ModifySql> getModifySql() {
            if (modifySql == null) {
                modifySql = new ArrayList<ModifySql>();
            }
            return this.modifySql;
        }

        /**
         * Gets the value of the id property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the author property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAuthor(String value) {
            this.author = value;
        }

        /**
         * Gets the value of the context property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getContext() {
            return context;
        }

        /**
         * Sets the value of the context property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setContext(String value) {
            this.context = value;
        }

        /**
         * Gets the value of the dbms property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDbms() {
            return dbms;
        }

        /**
         * Sets the value of the dbms property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDbms(String value) {
            this.dbms = value;
        }

        /**
         * Gets the value of the runOnChange property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRunOnChange() {
            return runOnChange;
        }

        /**
         * Sets the value of the runOnChange property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRunOnChange(String value) {
            this.runOnChange = value;
        }

        /**
         * Gets the value of the runAlways property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRunAlways() {
            return runAlways;
        }

        /**
         * Sets the value of the runAlways property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRunAlways(String value) {
            this.runAlways = value;
        }

        /**
         * Gets the value of the failOnError property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getFailOnError() {
            return failOnError;
        }

        /**
         * Sets the value of the failOnError property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setFailOnError(String value) {
            this.failOnError = value;
        }

        /**
         * Gets the value of the onValidationFail property.
         *
         * @return
         *     possible object is
         *     {@link OnChangeSetValidationFail }
         *
         */
        public OnChangeSetValidationFail getOnValidationFail() {
            return onValidationFail;
        }

        /**
         * Sets the value of the onValidationFail property.
         *
         * @param value
         *     allowed object is
         *     {@link OnChangeSetValidationFail }
         *
         */
        public void setOnValidationFail(OnChangeSetValidationFail value) {
            this.onValidationFail = value;
        }

        /**
         * Gets the value of the runInTransaction property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getRunInTransaction() {
            if (runInTransaction == null) {
                return "true";
            } else {
                return runInTransaction;
            }
        }

        /**
         * Sets the value of the runInTransaction property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setRunInTransaction(String value) {
            this.runInTransaction = value;
        }

        /**
         * Gets the value of the logicalFilePath property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLogicalFilePath() {
            return logicalFilePath;
        }

        /**
         * Sets the value of the logicalFilePath property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLogicalFilePath(String value) {
            this.logicalFilePath = value;
        }

        /**
         * Gets the value of the objectQuotingStrategy property.
         *
         * @return
         *     possible object is
         *     {@link ObjectQuotingStrategy }
         *
         */
        public ObjectQuotingStrategy getObjectQuotingStrategy() {
            return objectQuotingStrategy;
        }

        /**
         * Sets the value of the objectQuotingStrategy property.
         *
         * @param value
         *     allowed object is
         *     {@link ObjectQuotingStrategy }
         *
         */
        public void setObjectQuotingStrategy(ObjectQuotingStrategy value) {
            this.objectQuotingStrategy = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         *
         * <p>
         * the map is keyed by the name of the attribute and
         * the value is the string value of the attribute.
         *
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         *
         *
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}modifySqlChildren" maxOccurs="unbounded"/>
         *       &lt;/choice>
         *       &lt;attribute name="dbms" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="context" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="applyToRollback" type="{http://www.liquibase.org/xml/ns/dbchangelog}booleanExp" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "modifySqlChildren"
        })
        public static class ModifySql {

            @XmlElements({
                @XmlElement(name = "replace", type = DatabaseChangeLog.ChangeSet.ModifySql.Replace.class),
                @XmlElement(name = "regExpReplace", type = DatabaseChangeLog.ChangeSet.ModifySql.RegExpReplace.class),
                @XmlElement(name = "prepend", type = DatabaseChangeLog.ChangeSet.ModifySql.Prepend.class),
                @XmlElement(name = "append", type = DatabaseChangeLog.ChangeSet.ModifySql.Append.class)
            })
            protected List<Object> modifySqlChildren;
            @XmlAttribute(name = "dbms")
            protected String dbms;
            @XmlAttribute(name = "context")
            protected String context;
            @XmlAttribute(name = "applyToRollback")
            protected String applyToRollback;

            /**
             * Gets the value of the modifySqlChildren property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the modifySqlChildren property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getModifySqlChildren().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DatabaseChangeLog.ChangeSet.ModifySql.Replace }
             * {@link DatabaseChangeLog.ChangeSet.ModifySql.RegExpReplace }
             * {@link DatabaseChangeLog.ChangeSet.ModifySql.Prepend }
             * {@link DatabaseChangeLog.ChangeSet.ModifySql.Append }
             * 
             * 
             */
            public List<Object> getModifySqlChildren() {
                if (modifySqlChildren == null) {
                    modifySqlChildren = new ArrayList<Object>();
                }
                return this.modifySqlChildren;
            }

            /**
             * Gets the value of the dbms property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDbms() {
                return dbms;
            }

            /**
             * Sets the value of the dbms property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDbms(String value) {
                this.dbms = value;
            }

            /**
             * Gets the value of the context property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContext() {
                return context;
            }

            /**
             * Sets the value of the context property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContext(String value) {
                this.context = value;
            }

            /**
             * Gets the value of the applyToRollback property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApplyToRollback() {
                return applyToRollback;
            }

            /**
             * Sets the value of the applyToRollback property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApplyToRollback(String value) {
                this.applyToRollback = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Append {

                @XmlAttribute(name = "value", required = true)
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Prepend {

                @XmlAttribute(name = "value", required = true)
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="replace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="with" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class RegExpReplace {

                @XmlAttribute(name = "replace", required = true)
                protected String replace;
                @XmlAttribute(name = "with", required = true)
                protected String with;

                /**
                 * Gets the value of the replace property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReplace() {
                    return replace;
                }

                /**
                 * Sets the value of the replace property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReplace(String value) {
                    this.replace = value;
                }

                /**
                 * Gets the value of the with property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWith() {
                    return with;
                }

                /**
                 * Sets the value of the with property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWith(String value) {
                    this.with = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="replace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="with" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Replace {

                @XmlAttribute(name = "replace", required = true)
                protected String replace;
                @XmlAttribute(name = "with", required = true)
                protected String with;

                /**
                 * Gets the value of the replace property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReplace() {
                    return replace;
                }

                /**
                 * Sets the value of the replace property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReplace(String value) {
                    this.replace = value;
                }

                /**
                 * Gets the value of the with property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWith() {
                    return with;
                }

                /**
                 * Sets the value of the with property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWith(String value) {
                    this.with = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}PreConditionChildren" maxOccurs="unbounded"/>
         *       &lt;/choice>
         *       &lt;attribute name="onFailMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="onErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeSetPreconditionErrorOrFail" />
         *       &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeSetPreconditionErrorOrFail" />
         *       &lt;attribute name="onSqlOutput" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeLogPreconditionOnSqlOutput" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "preConditionChildren"
        })
        public static class PreConditions {

            @XmlElementRefs({
                @XmlElementRef(name = "tableIsEmpty", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = TableIsEmpty.class, required = false),
                @XmlElementRef(name = "rowCount", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RowCount.class, required = false),
                @XmlElementRef(name = "foreignKeyConstraintExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ForeignKeyConstraintExists.class, required = false),
                @XmlElementRef(name = "indexExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = IndexExists.class, required = false),
                @XmlElementRef(name = "customPrecondition", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CustomPrecondition.class, required = false),
                @XmlElementRef(name = "tableExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = TableExists.class, required = false),
                @XmlElementRef(name = "and", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = And.class, required = false),
                @XmlElementRef(name = "dbms", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Dbms.class, required = false),
                @XmlElementRef(name = "viewExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ViewExists.class, required = false),
                @XmlElementRef(name = "changeLogPropertyDefined", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ChangeLogPropertyDefined.class, required = false),
                @XmlElementRef(name = "changeSetExecuted", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ChangeSetExecuted.class, required = false),
                @XmlElementRef(name = "sqlCheck", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = SqlCheck.class, required = false),
                @XmlElementRef(name = "sequenceExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = SequenceExists.class, required = false),
                @XmlElementRef(name = "columnExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ColumnExists.class, required = false),
                @XmlElementRef(name = "or", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Or.class, required = false),
                @XmlElementRef(name = "not", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Not.class, required = false),
                @XmlElementRef(name = "runningAs", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RunningAs.class, required = false),
                @XmlElementRef(name = "expectedQuotingStrategy", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ExpectedQuotingStrategy.class, required = false),
                @XmlElementRef(name = "primaryKeyExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = PrimaryKeyExists.class, required = false)
            })
            @XmlAnyElement(lax = true)
            protected List<Object> preConditionChildren;
            @XmlAttribute(name = "onFailMessage")
            protected String onFailMessage;
            @XmlAttribute(name = "onErrorMessage")
            protected String onErrorMessage;
            @XmlAttribute(name = "onFail")
            protected OnChangeSetPreconditionErrorOrFail onFail;
            @XmlAttribute(name = "onError")
            protected OnChangeSetPreconditionErrorOrFail onError;
            @XmlAttribute(name = "onSqlOutput")
            protected OnChangeLogPreconditionOnSqlOutput onSqlOutput;

            /**
             * Gets the value of the preConditionChildren property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the preConditionChildren property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPreConditionChildren().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TableIsEmpty }
             * {@link RowCount }
             * {@link Element }
             * {@link ForeignKeyConstraintExists }
             * {@link IndexExists }
             * {@link CustomPrecondition }
             * {@link TableExists }
             * {@link And }
             * {@link Dbms }
             * {@link ViewExists }
             * {@link ChangeLogPropertyDefined }
             * {@link ChangeSetExecuted }
             * {@link SqlCheck }
             * {@link Object }
             * {@link SequenceExists }
             * {@link ColumnExists }
             * {@link Or }
             * {@link Not }
             * {@link RunningAs }
             * {@link ExpectedQuotingStrategy }
             * {@link PrimaryKeyExists }
             * 
             * 
             */
            public List<Object> getPreConditionChildren() {
                if (preConditionChildren == null) {
                    preConditionChildren = new ArrayList<Object>();
                }
                return this.preConditionChildren;
            }

            /**
             * Gets the value of the onFailMessage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOnFailMessage() {
                return onFailMessage;
            }

            /**
             * Sets the value of the onFailMessage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOnFailMessage(String value) {
                this.onFailMessage = value;
            }

            /**
             * Gets the value of the onErrorMessage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOnErrorMessage() {
                return onErrorMessage;
            }

            /**
             * Sets the value of the onErrorMessage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOnErrorMessage(String value) {
                this.onErrorMessage = value;
            }

            /**
             * Gets the value of the onFail property.
             * 
             * @return
             *     possible object is
             *     {@link OnChangeSetPreconditionErrorOrFail }
             *     
             */
            public OnChangeSetPreconditionErrorOrFail getOnFail() {
                return onFail;
            }

            /**
             * Sets the value of the onFail property.
             * 
             * @param value
             *     allowed object is
             *     {@link OnChangeSetPreconditionErrorOrFail }
             *     
             */
            public void setOnFail(OnChangeSetPreconditionErrorOrFail value) {
                this.onFail = value;
            }

            /**
             * Gets the value of the onError property.
             * 
             * @return
             *     possible object is
             *     {@link OnChangeSetPreconditionErrorOrFail }
             *     
             */
            public OnChangeSetPreconditionErrorOrFail getOnError() {
                return onError;
            }

            /**
             * Sets the value of the onError property.
             * 
             * @param value
             *     allowed object is
             *     {@link OnChangeSetPreconditionErrorOrFail }
             *     
             */
            public void setOnError(OnChangeSetPreconditionErrorOrFail value) {
                this.onError = value;
            }

            /**
             * Gets the value of the onSqlOutput property.
             * 
             * @return
             *     possible object is
             *     {@link OnChangeLogPreconditionOnSqlOutput }
             *     
             */
            public OnChangeLogPreconditionOnSqlOutput getOnSqlOutput() {
                return onSqlOutput;
            }

            /**
             * Sets the value of the onSqlOutput property.
             * 
             * @param value
             *     allowed object is
             *     {@link OnChangeLogPreconditionOnSqlOutput }
             *     
             */
            public void setOnSqlOutput(OnChangeLogPreconditionOnSqlOutput value) {
                this.onSqlOutput = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog}comment" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class ValidCheckSum {

            @XmlElementRef(name = "comment", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = JAXBElement.class, required = false)
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="relativeToChangelogFile" type="{http://www.liquibase.org/xml/ns/dbchangelog}booleanExp" />
     *       &lt;anyAttribute namespace='##other'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Include {

        @XmlAttribute(name = "file", required = true)
        protected String file;
        @XmlAttribute(name = "relativeToChangelogFile")
        protected String relativeToChangelogFile;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the relativeToChangelogFile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRelativeToChangelogFile() {
            return relativeToChangelogFile;
        }

        /**
         * Sets the value of the relativeToChangelogFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRelativeToChangelogFile(String value) {
            this.relativeToChangelogFile = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="relativeToChangelogFile" type="{http://www.liquibase.org/xml/ns/dbchangelog}booleanExp" />
     *       &lt;attribute name="resourceFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;anyAttribute namespace='##other'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IncludeAll {

        @XmlAttribute(name = "path", required = true)
        protected String path;
        @XmlAttribute(name = "relativeToChangelogFile")
        protected String relativeToChangelogFile;
        @XmlAttribute(name = "resourceFilter")
        protected String resourceFilter;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

        /**
         * Gets the value of the relativeToChangelogFile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRelativeToChangelogFile() {
            return relativeToChangelogFile;
        }

        /**
         * Sets the value of the relativeToChangelogFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRelativeToChangelogFile(String value) {
            this.relativeToChangelogFile = value;
        }

        /**
         * Gets the value of the resourceFilter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResourceFilter() {
            return resourceFilter;
        }

        /**
         * Sets the value of the resourceFilter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResourceFilter(String value) {
            this.resourceFilter = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}PreConditionChildren" maxOccurs="unbounded"/>
     *       &lt;/choice>
     *       &lt;attribute name="onFailMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="onErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeLogPreconditionErrorOrFail" />
     *       &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeLogPreconditionErrorOrFail" />
     *       &lt;attribute name="onSqlOutput" type="{http://www.liquibase.org/xml/ns/dbchangelog}onChangeLogPreconditionOnSqlOutput" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "preConditionChildren"
    })
    public static class PreConditions {

        @XmlElementRefs({
            @XmlElementRef(name = "tableIsEmpty", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = TableIsEmpty.class, required = false),
            @XmlElementRef(name = "rowCount", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RowCount.class, required = false),
            @XmlElementRef(name = "foreignKeyConstraintExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ForeignKeyConstraintExists.class, required = false),
            @XmlElementRef(name = "indexExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = IndexExists.class, required = false),
            @XmlElementRef(name = "customPrecondition", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CustomPrecondition.class, required = false),
            @XmlElementRef(name = "tableExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = TableExists.class, required = false),
            @XmlElementRef(name = "and", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = And.class, required = false),
            @XmlElementRef(name = "dbms", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Dbms.class, required = false),
            @XmlElementRef(name = "viewExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ViewExists.class, required = false),
            @XmlElementRef(name = "changeLogPropertyDefined", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ChangeLogPropertyDefined.class, required = false),
            @XmlElementRef(name = "changeSetExecuted", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ChangeSetExecuted.class, required = false),
            @XmlElementRef(name = "sqlCheck", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = SqlCheck.class, required = false),
            @XmlElementRef(name = "sequenceExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = SequenceExists.class, required = false),
            @XmlElementRef(name = "columnExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ColumnExists.class, required = false),
            @XmlElementRef(name = "or", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Or.class, required = false),
            @XmlElementRef(name = "not", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Not.class, required = false),
            @XmlElementRef(name = "runningAs", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RunningAs.class, required = false),
            @XmlElementRef(name = "expectedQuotingStrategy", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ExpectedQuotingStrategy.class, required = false),
            @XmlElementRef(name = "primaryKeyExists", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = PrimaryKeyExists.class, required = false)
        })
        @XmlAnyElement(lax = true)
        protected List<Object> preConditionChildren;
        @XmlAttribute(name = "onFailMessage")
        protected String onFailMessage;
        @XmlAttribute(name = "onErrorMessage")
        protected String onErrorMessage;
        @XmlAttribute(name = "onFail")
        protected OnChangeLogPreconditionErrorOrFail onFail;
        @XmlAttribute(name = "onError")
        protected OnChangeLogPreconditionErrorOrFail onError;
        @XmlAttribute(name = "onSqlOutput")
        protected OnChangeLogPreconditionOnSqlOutput onSqlOutput;

        /**
         * Gets the value of the preConditionChildren property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the preConditionChildren property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPreConditionChildren().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TableIsEmpty }
         * {@link RowCount }
         * {@link Element }
         * {@link ForeignKeyConstraintExists }
         * {@link IndexExists }
         * {@link CustomPrecondition }
         * {@link TableExists }
         * {@link And }
         * {@link Dbms }
         * {@link ViewExists }
         * {@link ChangeLogPropertyDefined }
         * {@link ChangeSetExecuted }
         * {@link SqlCheck }
         * {@link Object }
         * {@link SequenceExists }
         * {@link ColumnExists }
         * {@link Or }
         * {@link Not }
         * {@link RunningAs }
         * {@link ExpectedQuotingStrategy }
         * {@link PrimaryKeyExists }
         * 
         * 
         */
        public List<Object> getPreConditionChildren() {
            if (preConditionChildren == null) {
                preConditionChildren = new ArrayList<Object>();
            }
            return this.preConditionChildren;
        }

        /**
         * Gets the value of the onFailMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOnFailMessage() {
            return onFailMessage;
        }

        /**
         * Sets the value of the onFailMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOnFailMessage(String value) {
            this.onFailMessage = value;
        }

        /**
         * Gets the value of the onErrorMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOnErrorMessage() {
            return onErrorMessage;
        }

        /**
         * Sets the value of the onErrorMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOnErrorMessage(String value) {
            this.onErrorMessage = value;
        }

        /**
         * Gets the value of the onFail property.
         * 
         * @return
         *     possible object is
         *     {@link OnChangeLogPreconditionErrorOrFail }
         *     
         */
        public OnChangeLogPreconditionErrorOrFail getOnFail() {
            return onFail;
        }

        /**
         * Sets the value of the onFail property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnChangeLogPreconditionErrorOrFail }
         *     
         */
        public void setOnFail(OnChangeLogPreconditionErrorOrFail value) {
            this.onFail = value;
        }

        /**
         * Gets the value of the onError property.
         * 
         * @return
         *     possible object is
         *     {@link OnChangeLogPreconditionErrorOrFail }
         *     
         */
        public OnChangeLogPreconditionErrorOrFail getOnError() {
            return onError;
        }

        /**
         * Sets the value of the onError property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnChangeLogPreconditionErrorOrFail }
         *     
         */
        public void setOnError(OnChangeLogPreconditionErrorOrFail value) {
            this.onError = value;
        }

        /**
         * Gets the value of the onSqlOutput property.
         * 
         * @return
         *     possible object is
         *     {@link OnChangeLogPreconditionOnSqlOutput }
         *     
         */
        public OnChangeLogPreconditionOnSqlOutput getOnSqlOutput() {
            return onSqlOutput;
        }

        /**
         * Sets the value of the onSqlOutput property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnChangeLogPreconditionOnSqlOutput }
         *     
         */
        public void setOnSqlOutput(OnChangeLogPreconditionOnSqlOutput value) {
            this.onSqlOutput = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="dbms" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="context" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Property {

        @XmlAttribute(name = "file")
        protected String file;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "value")
        protected String value;
        @XmlAttribute(name = "dbms")
        protected String dbms;
        @XmlAttribute(name = "context")
        protected String context;

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the dbms property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDbms() {
            return dbms;
        }

        /**
         * Sets the value of the dbms property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDbms(String value) {
            this.dbms = value;
        }

        /**
         * Gets the value of the context property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContext() {
            return context;
        }

        /**
         * Sets the value of the context property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContext(String value) {
            this.context = value;
        }

    }

}
