//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 09:10:35 AM CEST 
//


package io.cloudtrust.keycloak.liquibaseAdapter.pojo.liquibase;

import org.w3c.dom.Element;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog}changeSetChildren" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="changeSetPath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="changeSetAuthor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="changeSetId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "rollback")
public class Rollback {

    @XmlElementRefs({
        @XmlElementRef(name = "sql", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Sql.class, required = false),
        @XmlElementRef(name = "insert", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Insert.class, required = false),
        @XmlElementRef(name = "dropIndex", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropIndex.class, required = false),
        @XmlElementRef(name = "addNotNullConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddNotNullConstraint.class, required = false),
        @XmlElementRef(name = "createView", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateView.class, required = false),
        @XmlElementRef(name = "renameTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RenameTable.class, required = false),
        @XmlElementRef(name = "dropForeignKeyConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropForeignKeyConstraint.class, required = false),
        @XmlElementRef(name = "rollback", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Rollback.class, required = false),
        @XmlElementRef(name = "loadData", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = LoadData.class, required = false),
        @XmlElementRef(name = "dropNotNullConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropNotNullConstraint.class, required = false),
        @XmlElementRef(name = "alterSequence", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AlterSequence.class, required = false),
        @XmlElementRef(name = "dropPrimaryKey", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropPrimaryKey.class, required = false),
        @XmlElementRef(name = "createSequence", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateSequence.class, required = false),
        @XmlElementRef(name = "addForeignKeyConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddForeignKeyConstraint.class, required = false),
        @XmlElementRef(name = "renameView", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RenameView.class, required = false),
        @XmlElementRef(name = "dropProcedure", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropProcedure.class, required = false),
        @XmlElementRef(name = "dropColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropColumn.class, required = false),
        @XmlElementRef(name = "createTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateTable.class, required = false),
        @XmlElementRef(name = "sqlFile", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = SqlFile.class, required = false),
        @XmlElementRef(name = "addUniqueConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddUniqueConstraint.class, required = false),
        @XmlElementRef(name = "dropView", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropView.class, required = false),
        @XmlElementRef(name = "mergeColumns", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = MergeColumns.class, required = false),
        @XmlElementRef(name = "stop", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Stop.class, required = false),
        @XmlElementRef(name = "update", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Update.class, required = false),
        @XmlElementRef(name = "dropTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropTable.class, required = false),
        @XmlElementRef(name = "executeCommand", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ExecuteCommand.class, required = false),
        @XmlElementRef(name = "createIndex", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateIndex.class, required = false),
        @XmlElementRef(name = "addLookupTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddLookupTable.class, required = false),
        @XmlElementRef(name = "modifyDataType", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = ModifyDataType.class, required = false),
        @XmlElementRef(name = "addPrimaryKey", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddPrimaryKey.class, required = false),
        @XmlElementRef(name = "addDefaultValue", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddDefaultValue.class, required = false),
        @XmlElementRef(name = "addAutoIncrement", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddAutoIncrement.class, required = false),
        @XmlElementRef(name = "renameColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = RenameColumn.class, required = false),
        @XmlElementRef(name = "dropSequence", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropSequence.class, required = false),
        @XmlElementRef(name = "empty", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "loadUpdateData", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = LoadUpdateData.class, required = false),
        @XmlElementRef(name = "addColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = AddColumn.class, required = false),
        @XmlElementRef(name = "dropAllForeignKeyConstraints", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropAllForeignKeyConstraints.class, required = false),
        @XmlElementRef(name = "dropDefaultValue", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropDefaultValue.class, required = false),
        @XmlElementRef(name = "customChange", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CustomChange.class, required = false),
        @XmlElementRef(name = "createProcedure", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = CreateProcedure.class, required = false),
        @XmlElementRef(name = "comment", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dropUniqueConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = DropUniqueConstraint.class, required = false),
        @XmlElementRef(name = "delete", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Delete.class, required = false)
    })
    @XmlMixed
    @XmlAnyElement(lax = true)
    protected List<Object> content;
    @XmlAttribute(name = "changeSetPath")
    protected String changeSetPath;
    @XmlAttribute(name = "changeSetAuthor")
    protected String changeSetAuthor;
    @XmlAttribute(name = "changeSetId")
    protected String changeSetId;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sql }
     * {@link Insert }
     * {@link DropIndex }
     * {@link Element }
     * {@link AddNotNullConstraint }
     * {@link CreateView }
     * {@link RenameTable }
     * {@link DropForeignKeyConstraint }
     * {@link Rollback }
     * {@link LoadData }
     * {@link DropNotNullConstraint }
     * {@link AlterSequence }
     * {@link DropPrimaryKey }
     * {@link CreateSequence }
     * {@link AddForeignKeyConstraint }
     * {@link RenameView }
     * {@link DropProcedure }
     * {@link DropColumn }
     * {@link CreateTable }
     * {@link SqlFile }
     * {@link AddUniqueConstraint }
     * {@link DropView }
     * {@link MergeColumns }
     * {@link Stop }
     * {@link Update }
     * {@link DropTable }
     * {@link ExecuteCommand }
     * {@link CreateIndex }
     * {@link AddLookupTable }
     * {@link Object }
     * {@link ModifyDataType }
     * {@link AddPrimaryKey }
     * {@link AddDefaultValue }
     * {@link AddAutoIncrement }
     * {@link RenameColumn }
     * {@link DropSequence }
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link LoadUpdateData }
     * {@link AddColumn }
     * {@link DropAllForeignKeyConstraints }
     * {@link DropDefaultValue }
     * {@link CustomChange }
     * {@link String }
     * {@link CreateProcedure }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link DropUniqueConstraint }
     * {@link Delete }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the changeSetPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeSetPath() {
        return changeSetPath;
    }

    /**
     * Sets the value of the changeSetPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeSetPath(String value) {
        this.changeSetPath = value;
    }

    /**
     * Gets the value of the changeSetAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeSetAuthor() {
        return changeSetAuthor;
    }

    /**
     * Sets the value of the changeSetAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeSetAuthor(String value) {
        this.changeSetAuthor = value;
    }

    /**
     * Gets the value of the changeSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeSetId() {
        return changeSetId;
    }

    /**
     * Sets the value of the changeSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeSetId(String value) {
        this.changeSetId = value;
    }

}
