//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 09:10:35 AM CEST 
//


package io.cloudtrust.keycloak.liquibaseAdapter.pojo.liquibase;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for columnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="columnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog}constraints" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog}column"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "columnType", propOrder = {
    "content"
})
@XmlSeeAlso({
        io.cloudtrust.keycloak.liquibaseAdapter.pojo.liquibase.AddColumn.Column.class
})
public class ColumnType {

    @XmlElementRef(name = "constraints", namespace = "http://www.liquibase.org/xml/ns/dbchangelog", type = Constraints.class, required = false)
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "value")
    protected String value;
    @XmlAttribute(name = "valueNumeric")
    protected String valueNumeric;
    @XmlAttribute(name = "valueBoolean")
    protected String valueBoolean;
    @XmlAttribute(name = "valueDate")
    protected String valueDate;
    @XmlAttribute(name = "valueComputed")
    protected String valueComputed;
    @XmlAttribute(name = "valueSequenceCurrent")
    protected String valueSequenceCurrent;
    @XmlAttribute(name = "valueSequenceNext")
    protected String valueSequenceNext;
    @XmlAttribute(name = "valueBlobFile")
    protected String valueBlobFile;
    @XmlAttribute(name = "valueClobFile")
    protected String valueClobFile;
    @XmlAttribute(name = "defaultValue")
    protected String defaultValue;
    @XmlAttribute(name = "defaultValueNumeric")
    protected String defaultValueNumeric;
    @XmlAttribute(name = "defaultValueDate")
    protected String defaultValueDate;
    @XmlAttribute(name = "defaultValueBoolean")
    protected String defaultValueBoolean;
    @XmlAttribute(name = "defaultValueComputed")
    protected String defaultValueComputed;
    @XmlAttribute(name = "defaultValueSequenceCurrent")
    protected String defaultValueSequenceCurrent;
    @XmlAttribute(name = "defaultValueSequenceNext")
    protected String defaultValueSequenceNext;
    @XmlAttribute(name = "autoIncrement")
    protected String autoIncrement;
    @XmlAttribute(name = "startWith")
    protected Long startWith;
    @XmlAttribute(name = "incrementBy")
    protected Long incrementBy;
    @XmlAttribute(name = "remarks")
    protected String remarks;
    @XmlAttribute(name = "encoding")
    protected String encoding;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Constraints }
     * {@link String }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the valueNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueNumeric() {
        return valueNumeric;
    }

    /**
     * Sets the value of the valueNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueNumeric(String value) {
        this.valueNumeric = value;
    }

    /**
     * Gets the value of the valueBoolean property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueBoolean() {
        return valueBoolean;
    }

    /**
     * Sets the value of the valueBoolean property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueBoolean(String value) {
        this.valueBoolean = value;
    }

    /**
     * Gets the value of the valueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDate() {
        return valueDate;
    }

    /**
     * Sets the value of the valueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDate(String value) {
        this.valueDate = value;
    }

    /**
     * Gets the value of the valueComputed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueComputed() {
        return valueComputed;
    }

    /**
     * Sets the value of the valueComputed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueComputed(String value) {
        this.valueComputed = value;
    }

    /**
     * Gets the value of the valueSequenceCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueSequenceCurrent() {
        return valueSequenceCurrent;
    }

    /**
     * Sets the value of the valueSequenceCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueSequenceCurrent(String value) {
        this.valueSequenceCurrent = value;
    }

    /**
     * Gets the value of the valueSequenceNext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueSequenceNext() {
        return valueSequenceNext;
    }

    /**
     * Sets the value of the valueSequenceNext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueSequenceNext(String value) {
        this.valueSequenceNext = value;
    }

    /**
     * Gets the value of the valueBlobFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueBlobFile() {
        return valueBlobFile;
    }

    /**
     * Sets the value of the valueBlobFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueBlobFile(String value) {
        this.valueBlobFile = value;
    }

    /**
     * Gets the value of the valueClobFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueClobFile() {
        return valueClobFile;
    }

    /**
     * Sets the value of the valueClobFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueClobFile(String value) {
        this.valueClobFile = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the defaultValueNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValueNumeric() {
        return defaultValueNumeric;
    }

    /**
     * Sets the value of the defaultValueNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValueNumeric(String value) {
        this.defaultValueNumeric = value;
    }

    /**
     * Gets the value of the defaultValueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValueDate() {
        return defaultValueDate;
    }

    /**
     * Sets the value of the defaultValueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValueDate(String value) {
        this.defaultValueDate = value;
    }

    /**
     * Gets the value of the defaultValueBoolean property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValueBoolean() {
        return defaultValueBoolean;
    }

    /**
     * Sets the value of the defaultValueBoolean property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValueBoolean(String value) {
        this.defaultValueBoolean = value;
    }

    /**
     * Gets the value of the defaultValueComputed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValueComputed() {
        return defaultValueComputed;
    }

    /**
     * Sets the value of the defaultValueComputed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValueComputed(String value) {
        this.defaultValueComputed = value;
    }

    /**
     * Gets the value of the defaultValueSequenceCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValueSequenceCurrent() {
        return defaultValueSequenceCurrent;
    }

    /**
     * Sets the value of the defaultValueSequenceCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValueSequenceCurrent(String value) {
        this.defaultValueSequenceCurrent = value;
    }

    /**
     * Gets the value of the defaultValueSequenceNext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValueSequenceNext() {
        return defaultValueSequenceNext;
    }

    /**
     * Sets the value of the defaultValueSequenceNext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValueSequenceNext(String value) {
        this.defaultValueSequenceNext = value;
    }

    /**
     * Gets the value of the autoIncrement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoIncrement() {
        return autoIncrement;
    }

    /**
     * Sets the value of the autoIncrement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoIncrement(String value) {
        this.autoIncrement = value;
    }

    /**
     * Gets the value of the startWith property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStartWith() {
        return startWith;
    }

    /**
     * Sets the value of the startWith property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStartWith(Long value) {
        this.startWith = value;
    }

    /**
     * Gets the value of the incrementBy property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIncrementBy() {
        return incrementBy;
    }

    /**
     * Sets the value of the incrementBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIncrementBy(Long value) {
        this.incrementBy = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncoding(String value) {
        this.encoding = value;
    }

}
