//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 09:10:35 AM CEST 
//


package io.cloudtrust.keycloak.liquibaseAdapter.pojo.liquibase;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fkCascadeActionOptions.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fkCascadeActionOptions">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="CASCADE"/>
 *     &lt;enumeration value="SET NULL"/>
 *     &lt;enumeration value="SET DEFAULT"/>
 *     &lt;enumeration value="RESTRICT"/>
 *     &lt;enumeration value="NO ACTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "fkCascadeActionOptions")
@XmlEnum
public enum FkCascadeActionOptions {

    CASCADE("CASCADE"),
    @XmlEnumValue("SET NULL")
    SET_NULL("SET NULL"),
    @XmlEnumValue("SET DEFAULT")
    SET_DEFAULT("SET DEFAULT"),
    RESTRICT("RESTRICT"),
    @XmlEnumValue("NO ACTION")
    NO_ACTION("NO ACTION");
    private final String value;

    FkCascadeActionOptions(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FkCascadeActionOptions fromValue(String v) {
        for (FkCascadeActionOptions c: FkCascadeActionOptions.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
