//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 09:10:35 AM CEST 
//


package io.cloudtrust.keycloak.liquibaseAdapter.pojo.liquibase;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for objectQuotingStrategy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="objectQuotingStrategy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LEGACY"/>
 *     &lt;enumeration value="QUOTE_ALL_OBJECTS"/>
 *     &lt;enumeration value="QUOTE_ONLY_RESERVED_WORDS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "objectQuotingStrategy")
@XmlEnum
public enum ObjectQuotingStrategy {

    LEGACY,
    QUOTE_ALL_OBJECTS,
    QUOTE_ONLY_RESERVED_WORDS;

    public String value() {
        return name();
    }

    public static ObjectQuotingStrategy fromValue(String v) {
        return valueOf(v);
    }

}
