//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 09:10:35 AM CEST 
//


package io.cloudtrust.keycloak.liquibaseAdapter.pojo.liquibase;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for onChangeSetPreconditionErrorOrFail.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="onChangeSetPreconditionErrorOrFail">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HALT"/>
 *     &lt;enumeration value="WARN"/>
 *     &lt;enumeration value="CONTINUE"/>
 *     &lt;enumeration value="MARK_RAN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "onChangeSetPreconditionErrorOrFail")
@XmlEnum
public enum OnChangeSetPreconditionErrorOrFail {

    HALT,
    WARN,
    CONTINUE,
    MARK_RAN;

    public String value() {
        return name();
    }

    public static OnChangeSetPreconditionErrorOrFail fromValue(String v) {
        return valueOf(v);
    }

}
