//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 09:10:35 AM CEST 
//


package io.cloudtrust.keycloak.liquibaseAdapter.pojo.liquibase;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog}param"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "param")
public class Param {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "value")
    protected String value;
    @XmlAttribute(name = "valueNumeric")
    protected String valueNumeric;
    @XmlAttribute(name = "valueBoolean")
    protected String valueBoolean;
    @XmlAttribute(name = "valueDate")
    protected String valueDate;
    @XmlAttribute(name = "valueComputed")
    protected String valueComputed;
    @XmlAttribute(name = "valueSequenceNext")
    protected String valueSequenceNext;
    @XmlAttribute(name = "valueSequenceCurrent")
    protected String valueSequenceCurrent;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the valueNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueNumeric() {
        return valueNumeric;
    }

    /**
     * Sets the value of the valueNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueNumeric(String value) {
        this.valueNumeric = value;
    }

    /**
     * Gets the value of the valueBoolean property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueBoolean() {
        return valueBoolean;
    }

    /**
     * Sets the value of the valueBoolean property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueBoolean(String value) {
        this.valueBoolean = value;
    }

    /**
     * Gets the value of the valueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDate() {
        return valueDate;
    }

    /**
     * Sets the value of the valueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDate(String value) {
        this.valueDate = value;
    }

    /**
     * Gets the value of the valueComputed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueComputed() {
        return valueComputed;
    }

    /**
     * Sets the value of the valueComputed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueComputed(String value) {
        this.valueComputed = value;
    }

    /**
     * Gets the value of the valueSequenceNext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueSequenceNext() {
        return valueSequenceNext;
    }

    /**
     * Sets the value of the valueSequenceNext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueSequenceNext(String value) {
        this.valueSequenceNext = value;
    }

    /**
     * Gets the value of the valueSequenceCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueSequenceCurrent() {
        return valueSequenceCurrent;
    }

    /**
     * Sets the value of the valueSequenceCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueSequenceCurrent(String value) {
        this.valueSequenceCurrent = value;
    }

}
